### ISSUE TITLE
Test & Deploy Current Version

### ISSUE THREAD

**Issue by dvdokkum** [WXYC/Backend-Service#15]
Hey @AyBruno! 

So just want to confirm here that what's currently here in `main` is not deployed to prod, and that the blocker for deploying is just testing all of the new changes that you pushed 2 months ago... correct or no?

**Comment by AyBruno** [comment]
@dvdokkum  That is correct. What's currently on main is not deployed. I do think it would be a good idea to test locally before deploying, but I would also feel comfortable deploying and testing on prod. Deploying itself is quite the blocker. It takes a while and AWS permissions are a pain. If you have any tips on how I could automate deployment of containers to the ec2 instance that would be huge.

**Comment by dvdokkum** [comment]
So just to circle back to this... there's now a deploy action in Github. By default it will dry-run and do the following:
- build the docker image
- compare that image to what is currently latest in ECR and indicate whether it is new
- show currently running images on the prod server

If you set the dry-run prop to `false` it will do the deploy as outline in the Readme:
- build and push to ECR
- pull latest on the prod server and restart

I haven't been able to test the actual deploy yet, so let me know when would be a good time (when we're ready to push main to prod) and I'll make sure it is working for real for real.

**Comment by AyBruno** [comment]
@dvdokkum The program at this point should build and compile successfully so we should be good to go with testing the deploy action out.

**Comment by dvdokkum** [comment]
great, i'll give it a shot now!

**Comment by dvdokkum** [comment]
ok that's done. what's on `main` has been deployed
